import type { GroupTemplate } from "./types";

export const defaultGroups: GroupTemplate[] = [
  {
    id: "supplier-to-factory",
    title: "Tedarikciden Fabrikaya",
    description: "Hammadde, tedarik ve ara transfer kaynakli emisyonlar",
    steps: [
      {
        id: "raw-material",
        label: "Hammadde Tasimasi",
        unit: "ton-km",
        factor: 0.12,
      },
      {
        id: "farm-fuel",
        label: "Tedarikcinin Tarim Faaliyetleri (Yakit)",
        unit: "litre",
        factor: 2.68,
      },
      {
        id: "farm-fertilizer",
        label: "Tedarikcinin Tarim Faaliyetleri (Gubre)",
        unit: "kg",
        factor: 1.75,
      },
      {
        id: "supplier-certification",
        label: "Tedarikci Sertifikasyon Sureci",
        unit: "adet",
        factor: 15,
      },
      {
        id: "road-intermediate",
        label: "Karayoluyla Ara Tedarikci Transferi",
        unit: "ton-km",
        factor: 0.1,
      },
      {
        id: "air-intermediate",
        label: "Havayoluyla Ara Tedarikci Transferi",
        unit: "ton-km",
        factor: 0.75,
      },
      {
        id: "sea-intermediate",
        label: "Denizyoluyla Ara Tedarikci Transferi",
        unit: "ton-km",
        factor: 0.02,
      },
      {
        id: "drying-process",
        label: "Kurutma Sureci",
        unit: "kWh",
        factor: 0.43,
      },
      {
        id: "cold-storage",
        label: "Soguk Hava Deposu Kullanimi",
        unit: "kWh",
        factor: 0.43,
      },
      {
        id: "sample-shipping",
        label: "Numune Tasima",
        unit: "kg-km",
        factor: 0.28,
      },
      {
        id: "lab-analysis",
        label: "Laboratuvar Analizi",
        unit: "adet",
        factor: 8,
      },
    ],
  },
  {
    id: "factory-inside",
    title: "Fabrika Ici",
    description: "Operasyon, enerji, seyahat ve atik kaynakli emisyonlar",
    steps: [
      {
        id: "road-business-trip",
        label: "Karayoluyla Is Gezisi",
        unit: "km",
        factor: 0.19,
      },
      {
        id: "air-business-trip",
        label: "Havayoluyla Is Gezisi",
        unit: "km",
        factor: 0.16,
      },
      {
        id: "sea-business-trip",
        label: "Denizyoluyla Is Gezisi",
        unit: "km",
        factor: 0.11,
      },
      { id: "accommodation", label: "Konaklama", unit: "gece", factor: 14 },
      {
        id: "natural-gas",
        label: "Dogalgaz Tuketimi",
        unit: "Sm3",
        factor: 1.9,
      },
      {
        id: "electricity",
        label: "Elektrik Tuketimi",
        unit: "kWh",
        factor: 0.43,
      },
      {
        id: "chemical-emissions",
        label: "Kimyasal Emisyonlar",
        unit: "kg",
        factor: 2.2,
      },
      {
        id: "diesel-forklift",
        label: "Dizel/Benzin Forklift",
        unit: "litre",
        factor: 2.6,
      },
      {
        id: "electric-forklift",
        label: "Elektrikli Forklift",
        unit: "kWh",
        factor: 0.43,
      },
      {
        id: "service-vehicles",
        label: "Tasima Servis Araclari",
        unit: "km",
        factor: 0.21,
      },
      {
        id: "organic-waste",
        label: "Organik Atiklar",
        unit: "kg",
        factor: 0.45,
      },
      {
        id: "cafeteria",
        label: "Kantin Yemekhanesi Emisyonlari",
        unit: "ogun",
        factor: 1.25,
      },
      { id: "cardboard", label: "Karton Ambalaj", unit: "kg", factor: 0.95 },
      {
        id: "visitor-emissions",
        label: "Gelen Misafirlerden Kaynakli Emisyonlar",
        unit: "kisi",
        factor: 2.8,
      },
    ],
  },
  {
    id: "factory-to-customer",
    title: "Fabrikadan Musteriye",
    description: "Sevkiyat, ihracat, depolama ve ters lojistik emisyonlari",
    steps: [
      {
        id: "truck-shipment",
        label: "Urun Sevkiyat Kamyonlari",
        unit: "ton-km",
        factor: 0.1,
      },
      {
        id: "sea-export",
        label: "Denizyolu Ihracat Tasimaciligi",
        unit: "ton-km",
        factor: 0.02,
      },
      {
        id: "air-export",
        label: "Havayolu Ihracat Tasimaciligi",
        unit: "ton-km",
        factor: 0.75,
      },
      {
        id: "warehouse-transfer",
        label: "Ara Depolar Arasi Transfer",
        unit: "ton-km",
        factor: 0.09,
      },
      {
        id: "distributor-vehicles",
        label: "Distributor Araclari",
        unit: "km",
        factor: 0.21,
      },
      {
        id: "outsourced-logistics",
        label: "Taseron Lojistik Firmalari",
        unit: "sevkiyat",
        factor: 19,
      },
      {
        id: "storage-energy",
        label: "Urunun Depolarda Tutuldugu Sure Boyunca Enerji Kullanimi",
        unit: "kWh",
        factor: 0.43,
      },
      {
        id: "returns",
        label: "Bozulmus veya Hatali Urunlerin Geri Donusu",
        unit: "kg",
        factor: 0.35,
      },
      {
        id: "waste-burning",
        label: "Tasimadan Kaynakli Atiklarin Yakilmasi",
        unit: "kg",
        factor: 2.9,
      },
    ],
  },
];
